Modul8
artur-borowiec/KursAkademiaAndroida pull request #7
Opened 2020-09-27 20:59 UTC by artur-borowiec

2020-10-10 18:55 UTC, keresmi requested changes
Dobra robota! Poprawę te metodę `setEpisodes` i możesz śmiało mergować 👍

2020-10-10 18:55 UTC, keresmi commented on app/src/main/java/pl/arturborowiec/kursakademiaandroida/features/episodes/presentation/EpisodeAdapter.kt
> +    fun setEpisodes(episodes: List<EpisodeDisplayable>) {
@artur-borowiec chyba znalazłem powód, dla którego nie wyświetla Ci się lista epizodów. Nie ma tutaj zdefiniowanej operacji, która by te epizody dodawała do listy :)

2020-10-10 18:55 UTC, keresmi commented on app/src/main/res/values/strings.xml
> +    <string name="hello_blank_fragment">Hello blank fragment</string>
Podejrzewam, że ten placeholder nie jest już do niczego potrzebny.

2020-10-11 17:36 UTC, artur-borowiec commented on app/src/main/res/values/strings.xml
> +    <string name="hello_blank_fragment">Hello blank fragment</string>
Usunięty

2020-10-11 17:37 UTC, artur-borowiec commented on app/src/main/java/pl/arturborowiec/kursakademiaandroida/features/episodes/presentation/EpisodeAdapter.kt
> +    fun setEpisodes(episodes: List<EpisodeDisplayable>) {
Racja, przeoczyłem. Ale już naprawione

2020-10-11 17:39 UTC, merged